import { Recipe } from '@/types'

export const localRecipes: Recipe[] = [
  {
    id: 'siddu-001',
    title: 'Siddu',
    slug: 'siddu',
    region: 'Himachal Pradesh',
    category: 'staple',
    diet: 'veg',
    prepTime: 90,
    cookTime: 25,
    servings: 6,
    description: 'Pillowy steamed wheat bread filled with poppy seeds, walnuts and jaggery — the soul food of Kullu and Mandi valleys, eaten with desi ghee and dal.',
    ingredients: [
      '3 cups whole wheat flour',
      '1 tsp active dry yeast',
      '1 tsp sugar',
      '½ tsp salt',
      '¾ cup warm water',
      '— FOR THE FILLING —',
      '3 tbsp poppy seeds (khus khus)',
      '3 tbsp crushed walnuts',
      '2 tbsp hemp seeds (bhang ke beej)',
      '2 tbsp grated coconut',
      '2 tbsp jaggery (gur), grated',
      '½ tsp cardamom powder',
      '1 tbsp ghee',
      '— TO SERVE —',
      '4 tbsp pure desi ghee',
      '1 cup yellow moong dal, cooked',
    ],
    steps: [
      'Dissolve sugar in ½ cup warm water, sprinkle yeast, stir and rest 10 minutes until frothy.',
      'Combine flour and salt. Add yeast mixture and knead, adding water gradually, until soft and pliable. Coat with ghee, cover and rest 1 hour until doubled.',
      'Dry-roast poppy seeds 2 min, crush coarsely. Mix with walnuts, hemp seeds, coconut, jaggery, cardamom and ghee.',
      'Divide dough into 6 balls. Flatten each into a 4-inch disc, add filling, seal edges tightly and press flat. Rest 15 min.',
      'Steam on a greased rack for 20–25 min until firm and springy. Do not lift lid during steaming.',
      'Score the top, pour generous desi ghee into the cut. Serve with hot dal.',
    ],
    tags: ['kullu', 'mandi', 'steamed', 'traditional', 'winter', 'festive'],
    thumbnail: { url: '', alt: 'Siddu — Himachali steamed bread' },
  },
  {
    id: 'dham-002',
    title: 'Himachali Dham',
    slug: 'himachali-dham',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 60,
    cookTime: 90,
    servings: 8,
    description: 'The grand festive thali of Himachal — rice, moong dal, rajma, kaddu, boor ki kadi and mittha served on leaf plates at weddings and festivals.',
    ingredients: [
      '2 cups basmati rice',
      '1 cup moong dal (yellow split)',
      '1 cup rajma (red kidney beans), soaked overnight',
      '250g yellow pumpkin (kaddu)',
      '— FOR BOOR KI KADI —',
      '1 cup boor (dried urad dal dumplings)',
      '2 cups curd, whisked',
      '2 tbsp gram flour (besan)',
      '1 tsp turmeric',
      '1 tsp red chilli powder',
      '2 tbsp mustard oil',
      '1 tsp cumin seeds',
      '— FOR MITTHA (SWEET RICE) —',
      '1 cup rice',
      '¾ cup sugar',
      '4 tbsp ghee',
      '½ tsp cardamom powder',
      '10 raisins, handful cashews',
    ],
    steps: [
      'Cook rajma in a pressure cooker with salt and turmeric until soft (4–5 whistles). Finish with a tempering of ghee, cumin and red chilli.',
      'Prepare moong dal: cook until soft, season with turmeric and salt, finish with ghee tempering.',
      'Cube pumpkin and cook with mustard oil, cumin, turmeric, red chilli and a pinch of amchur until tender.',
      'For boor ki kadi: whisk curd with besan, turmeric and salt. Heat mustard oil, fry soaked boor until golden. Add the curd mixture and simmer 20 min until thick.',
      'For mittha: fry cashews and raisins in ghee. Add rice (soaked 30 min), water and sugar. Cook until rice is done, stir in cardamom.',
      'Serve on a leaf plate (patthal): rice in centre, ringed by dal, rajma, kaddu, boor ki kadi, and mittha on the side.',
    ],
    tags: ['wedding', 'festival', 'thali', 'mandi', 'chamba', 'traditional'],
    thumbnail: { url: '', alt: 'Himachali Dham — festive thali' },
  },
  {
    id: 'chha-gosht-003',
    title: 'Chha Gosht',
    slug: 'chha-gosht',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'non-veg',
    prepTime: 30,
    cookTime: 60,
    servings: 4,
    description: 'Marinated lamb slow-cooked in a mustard-yoghurt gravy with aromatic whole spices — the pride of Himachali non-vegetarian cooking.',
    ingredients: [
      '750g lamb/mutton, bone-in pieces',
      '1 cup thick yoghurt',
      '3 tbsp mustard oil',
      '2 tbsp gram flour (besan)',
      '1 tbsp ginger-garlic paste',
      '1 tsp turmeric',
      '2 tsp red chilli powder',
      '1 tsp coriander powder',
      '1 tsp fennel powder (saunf)',
      '4 cloves, 2 bay leaves, 1 cinnamon stick',
      '2 black cardamoms',
      'Salt to taste',
      'Fresh coriander to garnish',
    ],
    steps: [
      'Whisk yoghurt with besan, turmeric, chilli powder, coriander and fennel until smooth.',
      'Marinate lamb in the yoghurt mixture and ginger-garlic paste for at least 2 hours, ideally overnight.',
      'Heat mustard oil in a heavy pan until smoking, then reduce. Add whole spices and sauté 30 seconds.',
      'Add the marinated lamb and cook on high heat 5 min, stirring constantly to seal in juices.',
      'Reduce heat, cover and slow-cook 45–50 min, stirring every 10 min, until meat is tender and gravy thickens.',
      'Garnish with coriander and serve with steamed rice or tandoori roti.',
    ],
    tags: ['lamb', 'mustard', 'kullu', 'non-veg', 'special-occasion'],
    thumbnail: { url: '', alt: 'Chha Gosht — Himachali lamb curry' },
  },
  {
    id: 'babru-004',
    title: 'Babru',
    slug: 'babru',
    region: 'Himachal Pradesh',
    category: 'snack',
    diet: 'veg',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    description: 'Crispy deep-fried flatbread stuffed with spiced black gram paste — a popular street snack and breakfast in Mandi and Kullu.',
    ingredients: [
      '2 cups whole wheat flour',
      '½ cup black gram (urad dal), soaked 4 hours',
      '1 tsp cumin seeds',
      '½ tsp fennel seeds',
      '½ tsp red chilli powder',
      '½ tsp garam masala',
      '1 tsp ginger, grated',
      'Salt to taste',
      'Oil for deep frying',
      'Tamarind chutney to serve',
    ],
    steps: [
      'Make a firm dough with flour, salt and water. Rest 20 min covered.',
      'Grind soaked urad dal coarsely. Mix with cumin, fennel, chilli powder, garam masala, ginger and salt.',
      'Divide dough into balls. Flatten each, place a spoonful of dal filling in centre, seal and roll into a disc.',
      'Deep fry in medium-hot oil until golden brown and crispy on both sides.',
      'Drain on paper towels and serve hot with tamarind chutney or imli ki chatni.',
    ],
    tags: ['mandi', 'street-food', 'breakfast', 'urad-dal', 'fried'],
    thumbnail: { url: '', alt: 'Babru — stuffed fried flatbread' },
  },
  {
    id: 'madra-005',
    title: 'Madra',
    slug: 'madra',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    description: 'A signature dish of the Dham — chickpeas or rajma slow-cooked in a rich yoghurt gravy fragrant with dried ginger, cardamom and ghee.',
    ingredients: [
      '1½ cups kabuli chana (white chickpeas), soaked overnight',
      '1½ cups thick yoghurt, whisked',
      '3 tbsp pure ghee',
      '1 tsp turmeric',
      '1 tsp red chilli powder',
      '1 tsp dried ginger powder (sonth)',
      '1 tsp fennel powder',
      '4 green cardamoms, crushed',
      '2 cloves',
      '1 small cinnamon stick',
      '2 bay leaves',
      'Salt to taste',
    ],
    steps: [
      'Pressure-cook soaked chickpeas with salt and turmeric for 3 whistles until tender but not mushy. Reserve the cooking water.',
      'Heat ghee, add bay leaves, cloves, cinnamon and cardamom. Sauté 30 seconds.',
      'Add whisked yoghurt gradually over low heat, stirring constantly to prevent splitting.',
      'Add chilli powder, sonth, and fennel. Cook the yoghurt gravy for 8–10 min until oil separates.',
      'Add cooked chickpeas and some reserved water. Simmer 15–20 min until gravy thickens and coats the chickpeas.',
      'Finish with a drizzle of ghee. Serve as part of Dham or with rice.',
    ],
    tags: ['chamba', 'kangra', 'dham', 'chickpeas', 'yoghurt-curry'],
    thumbnail: { url: '', alt: 'Madra — Himachali chickpea curry' },
  },
  {
    id: 'aktori-006',
    title: 'Aktori',
    slug: 'aktori',
    region: 'Himachal Pradesh',
    category: 'sweet',
    diet: 'veg',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    description: 'A traditional buckwheat pancake from the Spiti and Kinnaur valleys, lightly sweetened and eaten during festivals and cold winter mornings.',
    ingredients: [
      '2 cups buckwheat flour (kuttu ka atta)',
      '1 egg (or 2 tbsp flaxseed paste for vegan)',
      '1 cup water or milk',
      '2 tbsp jaggery, grated',
      '½ tsp cardamom powder',
      'Pinch of salt',
      '2 tbsp ghee for cooking',
    ],
    steps: [
      'Whisk buckwheat flour, egg/flaxseed paste, jaggery, cardamom and salt with water until a smooth, pourable batter forms.',
      'Rest the batter 10 minutes.',
      'Heat a griddle and brush with ghee. Pour a ladle of batter, spreading to a thin round.',
      'Cook on medium heat 2–3 min until edges lift and top is set. Flip and cook 1 min more.',
      'Serve warm with honey, fresh butter or walnut chutney.',
    ],
    tags: ['spiti', 'kinnaur', 'buckwheat', 'breakfast', 'winter', 'tribal'],
    thumbnail: { url: '', alt: 'Aktori — buckwheat pancake' },
  },
  {
    id: 'rajma-pahadi-007',
    title: 'Pahadi Rajma',
    slug: 'pahadi-rajma',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 15,
    cookTime: 50,
    servings: 4,
    description: 'Small, dark red mountain kidney beans slow-cooked in a tangy onion-tomato gravy — a staple comfort meal across Himachal households.',
    ingredients: [
      '1½ cups pahadi rajma (small red kidney beans), soaked overnight',
      '2 medium onions, finely chopped',
      '3 tomatoes, puréed',
      '1 tbsp ginger-garlic paste',
      '2 tsp coriander powder',
      '1 tsp cumin powder',
      '1 tsp red chilli powder',
      '½ tsp turmeric',
      '½ tsp garam masala',
      '3 tbsp mustard oil',
      'Salt to taste',
      'Fresh coriander to garnish',
    ],
    steps: [
      'Pressure-cook soaked rajma with salt and turmeric for 5 whistles until very soft.',
      'Heat mustard oil until smoking, reduce heat. Fry onions until deep golden, 12–15 min.',
      'Add ginger-garlic paste, cook 2 min. Add tomato purée and all dry spices. Cook until oil separates, 10 min.',
      'Add the cooked rajma with some cooking liquid. Simmer 20 min until gravy thickens.',
      'Finish with garam masala. Garnish with coriander. Serve with steamed rice and pickle.',
    ],
    tags: ['everyday', 'comfort-food', 'beans', 'rice', 'mustard-oil'],
    thumbnail: { url: '', alt: 'Pahadi Rajma' },
  },
  {
    id: 'sepu-badi-008',
    title: 'Sepu Badi',
    slug: 'sepu-badi',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 40,
    cookTime: 30,
    servings: 4,
    description: 'Crispy fried urad dal dumplings cooked with fresh spinach in a spiced yoghurt sauce — a beloved winter dish from the Kangra valley.',
    ingredients: [
      '1 cup urad dal (split black gram), soaked 5 hours',
      '400g fresh spinach, blanched and chopped',
      '1 cup thick yoghurt, whisked',
      '1 tbsp besan',
      '1 tsp turmeric',
      '1 tsp red chilli powder',
      '1 tsp coriander powder',
      '1 tsp ginger, grated',
      '3 tbsp mustard oil',
      '1 tsp cumin seeds',
      '2 dry red chillies',
      'Salt to taste',
    ],
    steps: [
      'Grind soaked urad dal to a thick paste. Season with salt, ginger and cumin. Shape into small cylindrical dumplings.',
      'Deep fry dumplings in hot oil until golden and crispy. Drain and soak in warm water 15 min, then squeeze out excess water.',
      'Heat mustard oil, add cumin and dry red chillies. Add spinach and sauté 5 min.',
      'Whisk yoghurt with besan, turmeric, chilli powder and coriander. Add to spinach over low heat, stirring constantly.',
      'Add soaked dumplings and simmer gently 15 min until gravy thickens and dumplings soften.',
      'Serve with hot phulkas or rice.',
    ],
    tags: ['kangra', 'spinach', 'urad-dal', 'winter', 'dumplings'],
    thumbnail: { url: '', alt: 'Sepu Badi — urad dal dumplings with spinach' },
  },
  {
    id: 'patande-009',
    title: 'Patande',
    slug: 'patande',
    region: 'Himachal Pradesh',
    category: 'sweet',
    diet: 'veg',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    description: 'Thin, crispy sweet pancakes made from whole wheat flour and jaggery — a beloved Himachali breakfast treat and festival snack.',
    ingredients: [
      '1½ cups whole wheat flour',
      '3 tbsp jaggery (gur), grated',
      '1 cup water',
      '½ tsp cardamom powder',
      '¼ tsp fennel seeds, crushed',
      'Pinch of salt',
      '2 tbsp ghee for cooking',
    ],
    steps: [
      'Mix flour, jaggery, cardamom, fennel and salt with enough water to make a thin, pourable batter.',
      'Rest 5 minutes for the jaggery to dissolve fully. Whisk well.',
      'Heat a flat tawa over medium heat. Brush with ghee.',
      'Pour a ladle of batter and spread thin. Cook until edges turn crispy and golden, about 2 min.',
      'Fold and serve immediately. Best eaten hot with a blob of fresh butter.',
    ],
    tags: ['breakfast', 'sweet', 'pancake', 'jaggery', 'kullu', 'shimla'],
    thumbnail: { url: '', alt: 'Patande — Himachali sweet pancakes' },
  },
  {
    id: 'dhaam-mittha-010',
    title: 'Mittha',
    slug: 'mittha',
    region: 'Himachal Pradesh',
    category: 'sweet',
    diet: 'veg',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    description: 'Sweet saffron rice cooked with ghee, raisins and dry fruits — the essential dessert served at every Himachali Dham and celebration.',
    ingredients: [
      '1½ cups basmati rice, soaked 30 min',
      '1 cup sugar',
      '5 tbsp pure ghee',
      '½ tsp saffron strands, soaked in 2 tbsp warm milk',
      '½ tsp cardamom powder',
      '2 tbsp raisins (kishmish)',
      '2 tbsp cashews, halved',
      '2 tbsp almonds, sliced',
      '2 cups water',
    ],
    steps: [
      'Heat ghee in a heavy pan. Fry cashews and almonds until golden. Remove and set aside.',
      'In the same ghee, add drained rice and sauté 3 min until translucent.',
      'Add water and sugar. Cook covered on low heat until water is absorbed and rice is nearly done.',
      'Drizzle saffron milk over the rice, scatter raisins and fried nuts. Cover tightly and steam on lowest heat 10 min.',
      'Fluff gently with a fork. The grains should be separate, golden and fragrant.',
    ],
    tags: ['dham', 'dessert', 'rice', 'saffron', 'festival', 'wedding'],
    thumbnail: { url: '', alt: 'Mittha — Himachali sweet rice' },
  },
  {
    id: 'bhagjery-011',
    title: 'Bhagjery',
    slug: 'bhagjery',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    description: 'A rustic, nourishing dal made from mixed lentils cooked with mustard oil and whole spices — a daily staple in Himachali village homes.',
    ingredients: [
      '½ cup masoor dal (red lentils)',
      '½ cup moong dal (yellow)',
      '¼ cup urad dal',
      '1 tsp turmeric',
      '1 tsp red chilli powder',
      '2 tbsp mustard oil',
      '1 tsp cumin seeds',
      '1 dry red chilli',
      '3 cloves garlic, minced',
      '1 tsp dried mango powder (amchur)',
      'Salt to taste',
      'Fresh coriander',
    ],
    steps: [
      'Wash and combine all three lentils. Pressure cook with 3 cups water, turmeric and salt for 2–3 whistles.',
      'Mash roughly. The consistency should be thick but pourable.',
      'Heat mustard oil to smoking, reduce. Add cumin, dry chilli and garlic. Fry until fragrant, 1 min.',
      'Pour the tempering over the dal. Add chilli powder and amchur.',
      'Simmer 5 min. Adjust consistency with water. Garnish with coriander.',
      'Serve with phulka, rice or as a side with Siddu.',
    ],
    tags: ['dal', 'everyday', 'village-food', 'lentils', 'mustard-oil'],
    thumbnail: { url: '', alt: 'Bhagjery — mixed lentil dal' },
  },
  {
    id: 'kullu-trout-012',
    title: 'Kullu Trout Curry',
    slug: 'kullu-trout-curry',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'non-veg',
    prepTime: 20,
    cookTime: 25,
    servings: 3,
    description: 'Fresh Beas river trout cooked in a light, tangy Himachali curry with mountain herbs and minimal spices to let the fish shine.',
    ingredients: [
      '500g fresh trout, cleaned and cut into steaks',
      '1 tsp turmeric',
      '1 tsp red chilli powder',
      '1 tbsp ginger paste',
      '2 tomatoes, finely chopped',
      '1 onion, sliced',
      '2 green chillies, slit',
      '1 tbsp dried fenugreek leaves (kasuri methi)',
      '3 tbsp mustard oil',
      '1 tsp cumin seeds',
      'Juice of ½ lemon',
      'Salt to taste',
    ],
    steps: [
      'Marinate trout with turmeric, chilli powder, ginger and salt for 15 min.',
      'Heat mustard oil to smoking, reduce. Add cumin and green chillies, sauté 30 sec.',
      'Add onion and fry until golden. Add tomatoes and cook until soft and oily.',
      'Place marinated trout pieces gently into the pan. Do not stir; let them cook 3–4 min per side.',
      'Sprinkle kasuri methi. Add ½ cup water, cover and simmer 5 min.',
      'Finish with lemon juice. Serve with steamed rice and salad.',
    ],
    tags: ['kullu', 'fish', 'beas-river', 'non-veg', 'protein'],
    thumbnail: { url: '', alt: 'Kullu Trout Curry' },
  },
  {
    id: 'khatta-013',
    title: 'Pahadi Khatta',
    slug: 'pahadi-khatta',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    description: 'A tangy-sweet tamarind curry with chickpeas or potatoes, seasoned with jaggery and whole spices — a signature dish of Himachali Dham.',
    ingredients: [
      '1 cup white chickpeas (or 2 medium potatoes, cubed)',
      '3 tbsp thick tamarind pulp',
      '2 tbsp jaggery',
      '2 tsp coriander powder',
      '1 tsp red chilli powder',
      '½ tsp turmeric',
      '1 tsp dry ginger powder (sonth)',
      '2 tbsp ghee',
      '1 tsp cumin seeds',
      '2 bay leaves',
      '1 black cardamom',
      'Salt to taste',
    ],
    steps: [
      'Cook chickpeas (or boil potatoes) until just tender.',
      'Mix tamarind pulp with jaggery, coriander powder, chilli, turmeric, sonth and salt. Taste — it should be tangy and slightly sweet.',
      'Heat ghee in a pan. Add cumin, bay leaves and black cardamom. Sauté 30 sec.',
      'Add the tamarind-jaggery mixture with ½ cup water. Simmer 5 min.',
      'Add cooked chickpeas/potatoes. Simmer 10 min until gravy thickens and coats everything.',
      'Serve as part of a thali or with puri.',
    ],
    tags: ['tamarind', 'sweet-sour', 'dham', 'chickpeas', 'chamba'],
    thumbnail: { url: '', alt: 'Pahadi Khatta — tamarind curry' },
  },
  {
    id: 'aloo-gutke-014',
    title: 'Aloo Ke Gutke',
    slug: 'aloo-ke-gutke',
    region: 'Himachal Pradesh',
    category: 'snack',
    diet: 'veg',
    prepTime: 10,
    cookTime: 20,
    servings: 3,
    description: 'Crispy spiced potatoes tossed with Pahadi dry chillies, coriander and amchur — the most popular street food snack across Himachal Pradesh.',
    ingredients: [
      '4 medium potatoes, boiled and cubed',
      '2 dry Pahadi red chillies, broken',
      '1 tsp cumin seeds',
      '½ tsp turmeric',
      '1 tsp coriander powder',
      '1 tsp amchur (dry mango powder)',
      '½ tsp red chilli powder',
      '2 tbsp mustard oil',
      'Salt to taste',
      'Fresh coriander to garnish',
    ],
    steps: [
      'Heat mustard oil in a wide pan until smoking, reduce heat.',
      'Add cumin seeds and broken dry chillies. Let them crackle 20 seconds.',
      'Add boiled potato cubes. Do not stir immediately — let them sit and form a crust, 3 min.',
      'Toss and add turmeric, coriander powder, chilli powder and salt. Mix well.',
      'Continue tossing on medium-high heat until potatoes are crispy and golden, about 8–10 min.',
      'Remove from heat, add amchur and coriander. Serve as a snack or side dish.',
    ],
    tags: ['street-food', 'potato', 'shimla', 'quick', 'snack', 'popular'],
    thumbnail: { url: '', alt: 'Aloo Ke Gutke' },
  },
  {
    id: 'mah-ki-dal-015',
    title: 'Mah Ki Dal',
    slug: 'mah-ki-dal',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 10,
    cookTime: 45,
    servings: 4,
    description: 'Whole black urad dal slow-cooked overnight in a clay pot with ghee and mountain spices — Himachal\'s version of the beloved dal makhani.',
    ingredients: [
      '1 cup whole urad dal (sabut kali dal), soaked overnight',
      '3 tbsp pure ghee',
      '1 onion, finely chopped',
      '1 tbsp ginger-garlic paste',
      '2 tomatoes, puréed',
      '1 tsp turmeric',
      '1½ tsp red chilli powder',
      '1 tsp coriander powder',
      '½ tsp garam masala',
      'Salt to taste',
      'Cream and coriander to garnish',
    ],
    steps: [
      'Pressure cook soaked urad dal with salt and turmeric for 6–8 whistles until completely soft.',
      'In a separate pan, heat ghee and fry onions until dark golden.',
      'Add ginger-garlic paste, cook 2 min. Add tomato purée and all dry spices. Cook 12 min until oil separates.',
      'Add cooked dal to the masala. Mix and simmer on very low heat 20–25 min, stirring regularly.',
      'The dal should be very creamy and thick. Adjust salt and finish with garam masala and a spoon of ghee.',
      'Garnish with cream and coriander. Serve with makki ki roti or rice.',
    ],
    tags: ['urad-dal', 'comfort', 'ghee', 'slow-cooked', 'winter'],
    thumbnail: { url: '', alt: 'Mah Ki Dal — whole black urad dal' },
  },
  {
    id: 'momos-pahadi-016',
    title: 'Pahadi Veg Momos',
    slug: 'pahadi-veg-momos',
    region: 'Himachal Pradesh',
    category: 'snack',
    diet: 'veg',
    prepTime: 45,
    cookTime: 15,
    servings: 4,
    description: 'Steamed dumplings stuffed with spiced cabbage, ginger and mountain herbs — a popular street snack in Dharamshala and Manali.',
    ingredients: [
      '2 cups all-purpose flour',
      '½ tsp salt',
      '¾ cup warm water',
      '— FOR FILLING —',
      '2 cups cabbage, finely shredded',
      '1 carrot, grated',
      '3 spring onions, chopped',
      '1 tbsp ginger, grated',
      '2 garlic cloves, minced',
      '2 tbsp soy sauce',
      '1 tsp sesame oil',
      '1 tsp black pepper',
      '— CHILLI DIPPING SAUCE —',
      '4 dry red chillies, soaked',
      '3 garlic cloves',
      '1 tsp vinegar',
      'Salt to taste',
    ],
    steps: [
      'Knead flour, salt and water into a firm dough. Rest 30 min covered.',
      'Mix all filling ingredients together. Season well.',
      'Roll dough into thin circles (10cm). Place filling in centre. Pleat and seal edges.',
      'Steam in a greased steamer basket for 12–15 min until wrappers turn translucent.',
      'Blend soaked red chillies, garlic, vinegar and salt for the dipping sauce.',
      'Serve hot momos with the spicy red chutney.',
    ],
    tags: ['dharamshala', 'manali', 'street-food', 'steamed', 'dumplings', 'popular'],
    thumbnail: { url: '', alt: 'Pahadi Veg Momos' },
  },
  {
    id: 'chutney-walnut-017',
    title: 'Pahadi Walnut Chutney',
    slug: 'pahadi-walnut-chutney',
    region: 'Himachal Pradesh',
    category: 'snack',
    diet: 'veg',
    prepTime: 10,
    cookTime: 0,
    servings: 6,
    description: 'A thick, creamy raw chutney of fresh walnuts, green coriander and mountain herbs — served with every Pahadi meal as a condiment.',
    ingredients: [
      '½ cup fresh walnut kernels',
      '1 cup fresh coriander leaves',
      '4 green chillies',
      '1 tsp ginger, grated',
      '2 cloves garlic',
      'Juice of 1 lemon',
      '½ tsp roasted cumin powder',
      'Salt to taste',
      '2–3 tbsp water (to blend)',
    ],
    steps: [
      'Soak walnuts in warm water 10 min to reduce bitterness. Drain.',
      'Blend walnuts, coriander, green chillies, ginger and garlic with a little water to a coarse paste.',
      'Season with lemon juice, roasted cumin and salt.',
      'Serve immediately alongside Siddu, Babru, momos or any Himachali meal.',
    ],
    tags: ['chutney', 'condiment', 'walnuts', 'raw', 'no-cook', 'accompaniment'],
    thumbnail: { url: '', alt: 'Pahadi Walnut Chutney' },
  },
  {
    id: 'tudkiya-bhath-018',
    title: 'Tudkiya Bhath',
    slug: 'tudkiya-bhath',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    description: 'A one-pot layered rice dish from Chamba — cooked with lentils, potatoes and Pahadi spices, similar to a mountain biryani.',
    ingredients: [
      '1½ cups basmati rice, soaked 20 min',
      '½ cup chana dal, soaked 2 hours',
      '2 medium potatoes, cubed',
      '1 onion, sliced',
      '2 tomatoes, chopped',
      '1 tbsp ginger-garlic paste',
      '1 tsp turmeric',
      '1½ tsp red chilli powder',
      '1 tsp garam masala',
      '3 tbsp mustard oil',
      '2 bay leaves, 3 cloves, 1 cinnamon stick',
      'Salt to taste',
      'Fresh coriander',
    ],
    steps: [
      'Heat mustard oil, add whole spices and fry onion until golden.',
      'Add ginger-garlic paste, tomatoes and all dry spices. Cook until oil separates.',
      'Add soaked chana dal and potatoes. Stir well and cook 5 min.',
      'Add soaked rice and 3 cups water. Season with salt.',
      'Bring to a boil, cover tightly and cook on very low heat 20 min until rice is done.',
      'Rest 5 min, fluff gently. Garnish with coriander and serve with raita.',
    ],
    tags: ['chamba', 'rice', 'one-pot', 'lentils', 'biryani-style'],
    thumbnail: { url: '', alt: 'Tudkiya Bhath — Himachali rice dish' },
  },
  {
    id: 'kachori-pahadi-019',
    title: 'Pahadi Kachori',
    slug: 'pahadi-kachori',
    region: 'Himachal Pradesh',
    category: 'snack',
    diet: 'veg',
    prepTime: 30,
    cookTime: 25,
    servings: 4,
    description: 'Flaky deep-fried pastry filled with spiced peas and dried herbs — a popular festival snack and tea-time treat across the Himachali hills.',
    ingredients: [
      '2 cups all-purpose flour',
      '3 tbsp ghee (for dough)',
      '½ tsp carom seeds (ajwain)',
      '½ cup water',
      '— FOR FILLING —',
      '1 cup green peas, mashed',
      '1 tsp cumin powder',
      '1 tsp coriander powder',
      '½ tsp red chilli powder',
      '½ tsp amchur',
      '1 tsp fennel seeds',
      'Salt to taste',
      'Oil for deep frying',
    ],
    steps: [
      'Rub ghee into flour with ajwain and salt until breadcrumb texture. Add water and knead into a firm dough. Rest 20 min.',
      'Mix all filling ingredients together.',
      'Divide dough into small balls. Roll each into a small disc. Place filling, seal well and roll very lightly.',
      'Deep fry in medium-hot oil, gently turning, until golden and crispy all over — about 6–8 min per batch.',
      'Drain and serve warm with green coriander chutney and tamarind chutney.',
    ],
    tags: ['snack', 'festival', 'tea-time', 'fried', 'peas', 'popular'],
    thumbnail: { url: '', alt: 'Pahadi Kachori' },
  },
  {
    id: 'til-rice-020',
    title: 'Til Rice',
    slug: 'til-rice',
    region: 'Himachal Pradesh',
    category: 'main',
    diet: 'veg',
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    description: 'Fragrant rice toasted with sesame seeds and ghee — a simple, nourishing Himachali dish often prepared during the Makar Sankranti festival.',
    ingredients: [
      '1½ cups basmati rice, soaked 20 min',
      '3 tbsp white sesame seeds (til)',
      '3 tbsp pure ghee',
      '1 tsp cumin seeds',
      '2 bay leaves',
      '½ tsp turmeric',
      'Salt to taste',
      '3 cups water',
    ],
    steps: [
      'Dry-roast sesame seeds in a pan until golden and fragrant, 2–3 min. Set aside.',
      'Heat ghee in a heavy pot. Add cumin, bay leaves and turmeric. Sauté 30 sec.',
      'Add drained rice and stir-fry 3 min until translucent and lightly toasted.',
      'Add water and salt. Bring to a boil, cover and cook on low heat 15 min.',
      'Remove from heat, rest 5 min. Fluff with a fork.',
      'Sprinkle toasted sesame seeds on top. Serve with curd and pickle.',
    ],
    tags: ['sesame', 'festival', 'makar-sankranti', 'rice', 'simple'],
    thumbnail: { url: '', alt: 'Til Rice — sesame rice' },
  },
]
